/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projektjakubdrozdide16;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;

/**
 *
 * @author drozd19100
 */
public class Kviz extends javax.swing.JFrame { //JFRAME ve kerém se zobrazují otázky

    ArrayList<Otazka> data;
    int indexAktOtazky=0; //index otázky, aby kdyz dojdou otázky tak se zobrazila obrazovka s vysledky, viz. DalsiActionPerformed
    int skore=0;
    boolean otazkaspravneDalsi = false;

    public void setSkore(int skore) {
        this.skore = skore;
    }
    /**
     * Creates new form Kviz
     */
    public Kviz() {
        initComponents();
        
        data = new ArrayList<Otazka>(); // pro nacitani otazek
        
        Scanner s =null;
        String radek;
        
        try { //zde se zapisuji otazky ze souboru do seznamu
            s = new Scanner(new FileInputStream("NacitaniOtazek.txt"));
        } 
        catch(FileNotFoundException e) { //pokud je soubor nefunkční
            System.out.println("soubor nenalezen");
            return;
        }
        
        while(s.hasNextLine()) { // zde se načítá po řádcích, vždy podle klicoveho slova na zacatku 
            radek=s.nextLine();
            
            if(radek.startsWith("#")) {
                radek=s.nextLine();
            }
            if(radek.startsWith("Nazev:")) {
                NazevKvizu.setText(radek.substring(6));
            }
            
            if(radek.startsWith("Otazka 1zN:")) {
                data.add(new Otazka(radek.substring(11)));
            }
            
             if(radek.startsWith("Spravne:")) {
                data.get(data.size()-1).addOdpoved(new Odpoved(true, radek.substring(8)));
             }
                
             if(radek.startsWith("Spatne:")) {
               data.get(data.size()-1).addOdpoved(new Odpoved(false, radek.substring(7)));
                 
            }
             
             if(radek.startsWith("Hodnota:")) { // nacita hodnotu, pokud to neprojde vypise error
                 try {
                 int hodnota = Integer.parseInt(radek.substring(8));
                 data.get(data.size()-1).setHodnota(hodnota);
                     } catch (NumberFormatException e) {
                            System.err.println("Chyba při převodu hodnoty na číslo");
    }
             }
            
        }
        
        Collections.shuffle(data);
        this.ZapisPomDoGUI(data.get(0));
    }
    
     public void ZapisPomDoGUI(Otazka o) {// tato funkce zapisuje otazky ze seznamu do GUI
         Collections.shuffle(o.odpovedi);
         TextOtazky.setText(o.otazka);
         Odpoved1.setText(o.odpovedi.get(0).textOdpovedi);
         Odpoved2.setText(o.odpovedi.get(1).textOdpovedi);
         Odpoved3.setText(o.odpovedi.get(2).textOdpovedi);
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TextOtazky = new javax.swing.JLabel();
        Odpoved1 = new javax.swing.JRadioButton();
        Odpoved2 = new javax.swing.JRadioButton();
        Odpoved3 = new javax.swing.JRadioButton();
        Dalsi = new javax.swing.JButton();
        NazevKvizu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(Odpoved1);
        Odpoved1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Odpoved1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Odpoved2);
        Odpoved2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Odpoved2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Odpoved3);
        Odpoved3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Odpoved3ActionPerformed(evt);
            }
        });

        Dalsi.setText("další");
        Dalsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DalsiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NazevKvizu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 294, Short.MAX_VALUE)
                .addComponent(Dalsi)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Odpoved3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Odpoved2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Odpoved1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextOtazky, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NazevKvizu, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextOtazky, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Odpoved1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Odpoved2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Odpoved3)
                .addGap(29, 29, 29)
                .addComponent(Dalsi)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Odpoved1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Odpoved1ActionPerformed
      if (data.get(indexAktOtazky).odpovedi.get(0).spravne) {
            otazkaspravneDalsi = true;
        }
      else {
          otazkaspravneDalsi = false;
      }
    }//GEN-LAST:event_Odpoved1ActionPerformed

    private void DalsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DalsiActionPerformed
        try {
            if(otazkaspravneDalsi) {
                skore += data.get(indexAktOtazky).getHodnota();
            }            
            indexAktOtazky += 1;
            ZapisPomDoGUI(data.get(indexAktOtazky));
            buttonGroup1.clearSelection();
        } catch (IndexOutOfBoundsException e) {
            ZobrazVysledky(skore); // Při vyčerpání otázek předejte celkové skóre
        }
    }
    static { //toto mi ze záhadného důvodu nejde smazat
    }//GEN-LAST:event_DalsiActionPerformed

    private void ZobrazVysledky(int skore) {
        gui.vysledkyFrame(this, "Vysledky", skore);
    }                                     
    
    
    private void Odpoved2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Odpoved2ActionPerformed
       if (data.get(indexAktOtazky).odpovedi.get(0).spravne) {
            otazkaspravneDalsi = true;
        }
      else {
          otazkaspravneDalsi = false;
      }
    }//GEN-LAST:event_Odpoved2ActionPerformed

    private void Odpoved3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Odpoved3ActionPerformed
        if (data.get(indexAktOtazky).odpovedi.get(0).spravne) {
            otazkaspravneDalsi = true;
        }
      else {
          otazkaspravneDalsi = false;
      }
    }//GEN-LAST:event_Odpoved3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kviz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kviz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kviz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kviz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kviz().setVisible(true);
            }
        });
    }

    GUImanager gui = new GUImanager();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dalsi;
    private javax.swing.JLabel NazevKvizu;
    private javax.swing.JRadioButton Odpoved1;
    private javax.swing.JRadioButton Odpoved2;
    private javax.swing.JRadioButton Odpoved3;
    private javax.swing.JLabel TextOtazky;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
