/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projektjakubdrozdide16;

import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author jakub
 */
public class UvodniObrazovka extends javax.swing.JFrame {
    GUImanager gui = new GUImanager();
    ArrayList<Otazka> list = new ArrayList<>();
    String NazevSouboru;

    public String getNazevSouboru() {
        return NazevSouboru;
    }
    
    /**
     * Creates new form UvodniObrazovka
     */
    public UvodniObrazovka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VyberSouboruText = new javax.swing.JTextField();
        VyberSouboruLabel = new javax.swing.JLabel();
        NacistSouborTlacitko = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Drozdova Úžasná Kvízová Aplikace");

        VyberSouboruText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VyberSouboruTextActionPerformed(evt);
            }
        });

        VyberSouboruLabel.setText("Vyber si soubor:");

        NacistSouborTlacitko.setText("Načíst Soubor a Spustit Kvíz");
        NacistSouborTlacitko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NacistSouborTlacitkoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(VyberSouboruLabel)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(VyberSouboruText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NacistSouborTlacitko)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(VyberSouboruLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VyberSouboruText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NacistSouborTlacitko)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NacistSouborTlacitkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NacistSouborTlacitkoActionPerformed
        FileReader fr = new FileReader();
        NazevSouboru = VyberSouboruText.getText();
        try {
            list = fr.nactiOtazky(NazevSouboru);
        } catch (EmptyFileException ex) {
            Logger.getLogger(UvodniObrazovka.class.getName()).log(Level.SEVERE, null, ex);
        }
        VyberSouboruText.setText("");
        VyberSouboruLabel.setText("Soubor načten");
        var resetSkore = new Kviz(list);
        resetSkore.setSkore(0);
        gui.dalsiFrame(resetSkore, "Kviz");
        this.dispose();
    }//GEN-LAST:event_NacistSouborTlacitkoActionPerformed

    private void VyberSouboruTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VyberSouboruTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VyberSouboruTextActionPerformed
    /**
     * @autor
     */
    public static void setFlatLaf() {
    try {
        UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
    } catch (UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(UvodniObrazovka.class.getName()).log(java.util.logging.Level.SEVERE, null,ex);
        System.err.println("Pravděpodobně tu hcybí knihovna lib/flatlaf-3.3.jar.");
        System.exit(1);
        }           
    }
    
    public static void setDefaultLaf() {
        try {
            for(UIManager.LookAndFeelInfo info: UIManager.getInstalledLookAndFeels()) {
                if("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UvodniObrazovka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            System.err.println("Nejde nastavit vzhled GTK+ ani Windows!");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        setFlatLaf();
        

    /**
     *
     */
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UvodniObrazovka().setVisible(true);
            }
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NacistSouborTlacitko;
    private javax.swing.JLabel VyberSouboruLabel;
    private javax.swing.JTextField VyberSouboruText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
